//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanji.Interface.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kanji.Interface.Internationalization.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to save the item. If the problem persists, please contact the support..
        /// </summary>
        internal static string SrsItem_EditFailure {
            get {
                return ResourceManager.GetString("SrsItem_EditFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item must have at least one meaning..
        /// </summary>
        internal static string SrsItem_MeaningsValidationError {
            get {
                return ResourceManager.GetString("SrsItem_MeaningsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item must have at least one reading..
        /// </summary>
        internal static string SrsItem_ReadingsValidationError {
            get {
                return ResourceManager.GetString("SrsItem_ReadingsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        internal static string VocabCat_Abbreviation {
            get {
                return ResourceManager.GetString("VocabCat_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjective.
        /// </summary>
        internal static string VocabCat_Adjective {
            get {
                return ResourceManager.GetString("VocabCat_Adjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverb.
        /// </summary>
        internal static string VocabCat_Adverb {
            get {
                return ResourceManager.GetString("VocabCat_Adverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverbial noun.
        /// </summary>
        internal static string VocabCat_AdverbialNoun {
            get {
                return ResourceManager.GetString("VocabCat_AdverbialNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anatomical term.
        /// </summary>
        internal static string VocabCat_Anatomy {
            get {
                return ResourceManager.GetString("VocabCat_Anatomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archaic verb.
        /// </summary>
        internal static string VocabCat_ArchaicVerb {
            get {
                return ResourceManager.GetString("VocabCat_ArchaicVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archaism.
        /// </summary>
        internal static string VocabCat_Archaism {
            get {
                return ResourceManager.GetString("VocabCat_Archaism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture term.
        /// </summary>
        internal static string VocabCat_Architecture {
            get {
                return ResourceManager.GetString("VocabCat_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomy term.
        /// </summary>
        internal static string VocabCat_Astronomy {
            get {
                return ResourceManager.GetString("VocabCat_Astronomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic.
        /// </summary>
        internal static string VocabCat_Ateji {
            get {
                return ResourceManager.GetString("VocabCat_Ateji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary.
        /// </summary>
        internal static string VocabCat_Auxiliary {
            get {
                return ResourceManager.GetString("VocabCat_Auxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary adjective.
        /// </summary>
        internal static string VocabCat_AuxiliaryAdjective {
            get {
                return ResourceManager.GetString("VocabCat_AuxiliaryAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary verb.
        /// </summary>
        internal static string VocabCat_AuxiliaryVerb {
            get {
                return ResourceManager.GetString("VocabCat_AuxiliaryVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseball term.
        /// </summary>
        internal static string VocabCat_Baseball {
            get {
                return ResourceManager.GetString("VocabCat_Baseball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biology term.
        /// </summary>
        internal static string VocabCat_Biology {
            get {
                return ResourceManager.GetString("VocabCat_Biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botany term.
        /// </summary>
        internal static string VocabCat_Botany {
            get {
                return ResourceManager.GetString("VocabCat_Botany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddhist term.
        /// </summary>
        internal static string VocabCat_BuddhistTerm {
            get {
                return ResourceManager.GetString("VocabCat_BuddhistTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business term.
        /// </summary>
        internal static string VocabCat_Business {
            get {
                return ResourceManager.GetString("VocabCat_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry term.
        /// </summary>
        internal static string VocabCat_Chemistry {
            get {
                return ResourceManager.GetString("VocabCat_Chemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s language.
        /// </summary>
        internal static string VocabCat_Children {
            get {
                return ResourceManager.GetString("VocabCat_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colloquialism.
        /// </summary>
        internal static string VocabCat_Colloquialism {
            get {
                return ResourceManager.GetString("VocabCat_Colloquialism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer term.
        /// </summary>
        internal static string VocabCat_ComputerTerminology {
            get {
                return ResourceManager.GetString("VocabCat_ComputerTerminology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjunction.
        /// </summary>
        internal static string VocabCat_Conjunction {
            get {
                return ResourceManager.GetString("VocabCat_Conjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string VocabCat_Counter {
            get {
                return ResourceManager.GetString("VocabCat_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derogative.
        /// </summary>
        internal static string VocabCat_Derogatory {
            get {
                return ResourceManager.GetString("VocabCat_Derogatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economics term.
        /// </summary>
        internal static string VocabCat_Economy {
            get {
                return ResourceManager.GetString("VocabCat_Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering term.
        /// </summary>
        internal static string VocabCat_Engineering {
            get {
                return ResourceManager.GetString("VocabCat_Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusively kana.
        /// </summary>
        internal static string VocabCat_ExclusivelyKana {
            get {
                return ResourceManager.GetString("VocabCat_ExclusivelyKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusively kanji.
        /// </summary>
        internal static string VocabCat_ExclusivelyKanji {
            get {
                return ResourceManager.GetString("VocabCat_ExclusivelyKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        internal static string VocabCat_Expression {
            get {
                return ResourceManager.GetString("VocabCat_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familiar.
        /// </summary>
        internal static string VocabCat_Familiar {
            get {
                return ResourceManager.GetString("VocabCat_Familiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female term.
        /// </summary>
        internal static string VocabCat_Female {
            get {
                return ResourceManager.GetString("VocabCat_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance term.
        /// </summary>
        internal static string VocabCat_Finance {
            get {
                return ResourceManager.GetString("VocabCat_Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food term.
        /// </summary>
        internal static string VocabCat_Food {
            get {
                return ResourceManager.GetString("VocabCat_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geology term.
        /// </summary>
        internal static string VocabCat_Geology {
            get {
                return ResourceManager.GetString("VocabCat_Geology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry term.
        /// </summary>
        internal static string VocabCat_Geometry {
            get {
                return ResourceManager.GetString("VocabCat_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special reading.
        /// </summary>
        internal static string VocabCat_Gikun {
            get {
                return ResourceManager.GetString("VocabCat_Gikun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerb {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -aru godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbAru {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbAru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -bu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbBu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -gu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbGu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbGu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -iku godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbIku {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbIku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ku godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbKu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbKu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -mu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbMu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbMu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -nu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbNu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbNu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ru godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbRu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irr. -ru godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbRuIrregular {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbRuIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -su godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbSu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -tsu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbTsu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbTsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -u godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbU {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irr. -u godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbUIrregular {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbUIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -uru godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbUru {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbUru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hokkaido-ben.
        /// </summary>
        internal static string VocabCat_HokkaidoBen {
            get {
                return ResourceManager.GetString("VocabCat_HokkaidoBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorific.
        /// </summary>
        internal static string VocabCat_Honorific {
            get {
                return ResourceManager.GetString("VocabCat_Honorific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humble.
        /// </summary>
        internal static string VocabCat_Humble {
            get {
                return ResourceManager.GetString("VocabCat_Humble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -i adjective.
        /// </summary>
        internal static string VocabCat_IAdjective {
            get {
                return ResourceManager.GetString("VocabCat_IAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ichidan verb.
        /// </summary>
        internal static string VocabCat_IchidanVerb {
            get {
                return ResourceManager.GetString("VocabCat_IchidanVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -zuru ichidan verb.
        /// </summary>
        internal static string VocabCat_IchidanVerbZuru {
            get {
                return ResourceManager.GetString("VocabCat_IchidanVerbZuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomatic expression.
        /// </summary>
        internal static string VocabCat_Idiomatic {
            get {
                return ResourceManager.GetString("VocabCat_Idiomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interjection.
        /// </summary>
        internal static string VocabCat_Interjection {
            get {
                return ResourceManager.GetString("VocabCat_Interjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intransitive.
        /// </summary>
        internal static string VocabCat_IntransitiveVerb {
            get {
                return ResourceManager.GetString("VocabCat_IntransitiveVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular kana usage.
        /// </summary>
        internal static string VocabCat_IrregularKanaUsage {
            get {
                return ResourceManager.GetString("VocabCat_IrregularKanaUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular kanji usage.
        /// </summary>
        internal static string VocabCat_IrregularKanjiUsage {
            get {
                return ResourceManager.GetString("VocabCat_IrregularKanjiUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular okurigana.
        /// </summary>
        internal static string VocabCat_IrregularOkuriganaUsage {
            get {
                return ResourceManager.GetString("VocabCat_IrregularOkuriganaUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular verb.
        /// </summary>
        internal static string VocabCat_IrregularVerb {
            get {
                return ResourceManager.GetString("VocabCat_IrregularVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humorous term.
        /// </summary>
        internal static string VocabCat_Jocular {
            get {
                return ResourceManager.GetString("VocabCat_Jocular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kansai-ben.
        /// </summary>
        internal static string VocabCat_KansaiBen {
            get {
                return ResourceManager.GetString("VocabCat_KansaiBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kantou-ben.
        /// </summary>
        internal static string VocabCat_KantouBen {
            get {
                return ResourceManager.GetString("VocabCat_KantouBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -kari adjective (arch.).
        /// </summary>
        internal static string VocabCat_KariAdjective {
            get {
                return ResourceManager.GetString("VocabCat_KariAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ku adjective (arch.).
        /// </summary>
        internal static string VocabCat_KuAdjective {
            get {
                return ResourceManager.GetString("VocabCat_KuAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuru verb.
        /// </summary>
        internal static string VocabCat_KuruVerb {
            get {
                return ResourceManager.GetString("VocabCat_KuruVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyoto-ben.
        /// </summary>
        internal static string VocabCat_KyotoBen {
            get {
                return ResourceManager.GetString("VocabCat_KyotoBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyuushuu-ben.
        /// </summary>
        internal static string VocabCat_KyuushuuBen {
            get {
                return ResourceManager.GetString("VocabCat_KyuushuuBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law term.
        /// </summary>
        internal static string VocabCat_Law {
            get {
                return ResourceManager.GetString("VocabCat_Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguistics term.
        /// </summary>
        internal static string VocabCat_Linguistics {
            get {
                return ResourceManager.GetString("VocabCat_Linguistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male term.
        /// </summary>
        internal static string VocabCat_Male {
            get {
                return ResourceManager.GetString("VocabCat_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male slang.
        /// </summary>
        internal static string VocabCat_MaleSlang {
            get {
                return ResourceManager.GetString("VocabCat_MaleSlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga slang.
        /// </summary>
        internal static string VocabCat_MangaSlang {
            get {
                return ResourceManager.GetString("VocabCat_MangaSlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial arts term.
        /// </summary>
        internal static string VocabCat_MartialArts {
            get {
                return ResourceManager.GetString("VocabCat_MartialArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematics term.
        /// </summary>
        internal static string VocabCat_Mathematics {
            get {
                return ResourceManager.GetString("VocabCat_Mathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine term.
        /// </summary>
        internal static string VocabCat_Medicine {
            get {
                return ResourceManager.GetString("VocabCat_Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military term.
        /// </summary>
        internal static string VocabCat_Military {
            get {
                return ResourceManager.GetString("VocabCat_Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music term.
        /// </summary>
        internal static string VocabCat_Music {
            get {
                return ResourceManager.GetString("VocabCat_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -na adjective.
        /// </summary>
        internal static string VocabCat_NaAdjective {
            get {
                return ResourceManager.GetString("VocabCat_NaAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagano-ben.
        /// </summary>
        internal static string VocabCat_NaganoBen {
            get {
                return ResourceManager.GetString("VocabCat_NaganoBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -nari adjective (arch.).
        /// </summary>
        internal static string VocabCat_NariAdjective {
            get {
                return ResourceManager.GetString("VocabCat_NariAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -u nidan verb.
        /// </summary>
        internal static string VocabCat_NidanVerbU {
            get {
                return ResourceManager.GetString("VocabCat_NidanVerbU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no-adjective noun.
        /// </summary>
        internal static string VocabCat_NoAdjective {
            get {
                return ResourceManager.GetString("VocabCat_NoAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noun.
        /// </summary>
        internal static string VocabCat_Noun {
            get {
                return ResourceManager.GetString("VocabCat_Noun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string VocabCat_Numeric {
            get {
                return ResourceManager.GetString("VocabCat_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irr. nu verb.
        /// </summary>
        internal static string VocabCat_NuVerb {
            get {
                return ResourceManager.GetString("VocabCat_NuVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obscure term.
        /// </summary>
        internal static string VocabCat_Obscure {
            get {
                return ResourceManager.GetString("VocabCat_Obscure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete.
        /// </summary>
        internal static string VocabCat_Obsolete {
            get {
                return ResourceManager.GetString("VocabCat_Obsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular kana.
        /// </summary>
        internal static string VocabCat_OldOrIrregularKana {
            get {
                return ResourceManager.GetString("VocabCat_OldOrIrregularKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onomatopoeia.
        /// </summary>
        internal static string VocabCat_Onomatopoeic {
            get {
                return ResourceManager.GetString("VocabCat_Onomatopoeic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osaka-ben.
        /// </summary>
        internal static string VocabCat_OsakaBen {
            get {
                return ResourceManager.GetString("VocabCat_OsakaBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated kana usage.
        /// </summary>
        internal static string VocabCat_OutdatedKana {
            get {
                return ResourceManager.GetString("VocabCat_OutdatedKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated kanji usage.
        /// </summary>
        internal static string VocabCat_OutdatedKanji {
            get {
                return ResourceManager.GetString("VocabCat_OutdatedKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle.
        /// </summary>
        internal static string VocabCat_Particle {
            get {
                return ResourceManager.GetString("VocabCat_Particle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics term.
        /// </summary>
        internal static string VocabCat_Physics {
            get {
                return ResourceManager.GetString("VocabCat_Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poetical term.
        /// </summary>
        internal static string VocabCat_Poetical {
            get {
                return ResourceManager.GetString("VocabCat_Poetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polite.
        /// </summary>
        internal static string VocabCat_Polite {
            get {
                return ResourceManager.GetString("VocabCat_Polite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string VocabCat_Prefix {
            get {
                return ResourceManager.GetString("VocabCat_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix noun.
        /// </summary>
        internal static string VocabCat_PrefixNoun {
            get {
                return ResourceManager.GetString("VocabCat_PrefixNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenominal adjective.
        /// </summary>
        internal static string VocabCat_PrenominalAdjective {
            get {
                return ResourceManager.GetString("VocabCat_PrenominalAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenominal.
        /// </summary>
        internal static string VocabCat_PrenominalNounVerb {
            get {
                return ResourceManager.GetString("VocabCat_PrenominalNounVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronoun.
        /// </summary>
        internal static string VocabCat_Pronoun {
            get {
                return ResourceManager.GetString("VocabCat_Pronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper noun.
        /// </summary>
        internal static string VocabCat_ProperNoun {
            get {
                return ResourceManager.GetString("VocabCat_ProperNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proverb.
        /// </summary>
        internal static string VocabCat_Proverb {
            get {
                return ResourceManager.GetString("VocabCat_Proverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string VocabCat_Rare {
            get {
                return ResourceManager.GetString("VocabCat_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irr. ru verb (plain form ends with -ri).
        /// </summary>
        internal static string VocabCat_RuVerb {
            get {
                return ResourceManager.GetString("VocabCat_RuVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ryuukyuu-ben.
        /// </summary>
        internal static string VocabCat_RyuukyuuBen {
            get {
                return ResourceManager.GetString("VocabCat_RyuukyuuBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitive.
        /// </summary>
        internal static string VocabCat_Sensitive {
            get {
                return ResourceManager.GetString("VocabCat_Sensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -shiku adjective (arch.).
        /// </summary>
        internal static string VocabCat_ShikuAdjective {
            get {
                return ResourceManager.GetString("VocabCat_ShikuAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shinto term.
        /// </summary>
        internal static string VocabCat_Shinto {
            get {
                return ResourceManager.GetString("VocabCat_Shinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slang.
        /// </summary>
        internal static string VocabCat_Slang {
            get {
                return ResourceManager.GetString("VocabCat_Slang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports term.
        /// </summary>
        internal static string VocabCat_Sports {
            get {
                return ResourceManager.GetString("VocabCat_Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string VocabCat_Suffix {
            get {
                return ResourceManager.GetString("VocabCat_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix noun.
        /// </summary>
        internal static string VocabCat_SuffixNoun {
            get {
                return ResourceManager.GetString("VocabCat_SuffixNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumo term.
        /// </summary>
        internal static string VocabCat_Sumo {
            get {
                return ResourceManager.GetString("VocabCat_Sumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -suru verb.
        /// </summary>
        internal static string VocabCat_SuruVerb {
            get {
                return ResourceManager.GetString("VocabCat_SuruVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irr. -suru verb.
        /// </summary>
        internal static string VocabCat_SuruVerbIrregular {
            get {
                return ResourceManager.GetString("VocabCat_SuruVerbIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -suru verb.
        /// </summary>
        internal static string VocabCat_SuruVerbNoun {
            get {
                return ResourceManager.GetString("VocabCat_SuruVerbNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -su verb.
        /// </summary>
        internal static string VocabCat_SuVerb {
            get {
                return ResourceManager.GetString("VocabCat_SuVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -taru adjective.
        /// </summary>
        internal static string VocabCat_TaruAdjective {
            get {
                return ResourceManager.GetString("VocabCat_TaruAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal noun.
        /// </summary>
        internal static string VocabCat_TemporalNoun {
            get {
                return ResourceManager.GetString("VocabCat_TemporalNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -to adverb.
        /// </summary>
        internal static string VocabCat_ToAdverb {
            get {
                return ResourceManager.GetString("VocabCat_ToAdverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosa-ben.
        /// </summary>
        internal static string VocabCat_TosaBen {
            get {
                return ResourceManager.GetString("VocabCat_TosaBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhoku-ben.
        /// </summary>
        internal static string VocabCat_TouhokuBen {
            get {
                return ResourceManager.GetString("VocabCat_TouhokuBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitive.
        /// </summary>
        internal static string VocabCat_TransitiveVerb {
            get {
                return ResourceManager.GetString("VocabCat_TransitiveVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsugaru-ben.
        /// </summary>
        internal static string VocabCat_TsugaruBen {
            get {
                return ResourceManager.GetString("VocabCat_TsugaruBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually written in kana.
        /// </summary>
        internal static string VocabCat_UsuallyKana {
            get {
                return ResourceManager.GetString("VocabCat_UsuallyKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually written in kanji.
        /// </summary>
        internal static string VocabCat_UsuallyKanji {
            get {
                return ResourceManager.GetString("VocabCat_UsuallyKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb.
        /// </summary>
        internal static string VocabCat_Verb {
            get {
                return ResourceManager.GetString("VocabCat_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulgar.
        /// </summary>
        internal static string VocabCat_Vulgar {
            get {
                return ResourceManager.GetString("VocabCat_Vulgar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-rated term.
        /// </summary>
        internal static string VocabCat_X {
            get {
                return ResourceManager.GetString("VocabCat_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -fu yodan verb.
        /// </summary>
        internal static string VocabCat_YodanVerbFu {
            get {
                return ResourceManager.GetString("VocabCat_YodanVerbFu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ru yodan verb.
        /// </summary>
        internal static string VocabCat_YodanVerbRu {
            get {
                return ResourceManager.GetString("VocabCat_YodanVerbRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoology term.
        /// </summary>
        internal static string VocabCat_Zoology {
            get {
                return ResourceManager.GetString("VocabCat_Zoology", resourceCulture);
            }
        }
    }
}
